import { Merriweather, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const merriweatherFont = Merriweather({
	variable: "--font-merriweather-sans",
	subsets: ["latin"],
});

const jetbrainsFont = JetBrains_Mono({
	variable: "--font-jetbrain-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${merriweatherFont.variable} ${jetbrainsFont.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
